name: Repo Test

on: push

env:
  TOLAN_CLONE_PATH: ''

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Unity repo
        uses: actions/checkout@v4
        with:
          repository: 'raguirreg10/PrivateRepo'
          ssh-key: ${{ secrets.SSK_KEY }} 

      - name: Download Tolan Code
        if: env.TOLAN_CLONE_PATH == ''
        uses: actions/checkout@v4
        with:
          path: TolanLab

      - name: List files
        run: |
          ls -la
          ls -la TolanLab

      
