name: Repo Test

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone another repo
        uses: actions/checkout@v4
        with:
          repository: 'raguirreg10/PrivateRepo'
          ssh-key: ${{ secrets.SSK_KEY }} 

      - name: List files
        run: ls -la
