name: Repo Test

on: push

env:
  TOLAN_CLONE_PATH: ''

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone another repo
        uses: actions/checkout@v4
        with:
          repository: 'raguirreg10/PrivateRepo'
          ssh-key: ${{ secrets.SSK_KEY }} 

      - name: Print TolanLab path
        run: echo ${{ env.TOLAN-DIR-PATH }} 

      - name: Download Tolan Code
        uses: actions/checkout@v4
        with:
          path: TolanLab

      - name: List files
        run: |
          ls -la
          ls -la TolanLab

      - name: Overwrite Env
        run: |
          TOLAN_CLONE_PATH_TEMP=$(mktemp -d) 
          echo "TOLAN_CLONE_PATH=$TOLAN_CLONE_PATH_TEMP" >> $GITHUB_ENV

      - name: print env
        run: echo $TOLAN_CLONE_PATH

      
