name: Repo Test

inputs:
  TOLAN_DIR_PATH:
    description: 'Location of Tolan clone repo, if empty a temp dir will be created'
    required: false

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone another repo
        uses: actions/checkout@v4
        with:
          repository: 'raguirreg10/PrivateRepo'
          ssh-key: ${{ secrets.SSK_KEY }} 

      - name: List files
        run: ls -la

      - name: Print TolanLab path
        run: echo ${{ inputs.TOLAN_DIR_PATH }} 
